#! /bin/bash
#SBATCH -c 4
#SBATCH --partition=smem
#SBATCH --qos=normal
#SBATCH -t 3-00:00:00
#SBATCH -N 1
#SBATCH --mail-type=END
#SBATCH --mail-user=evan.conaway@gmail.com
#SBATCH --array=0-2
#SBATCH --mem=40000
#SBATCH --mail-type=BEGIN
ml jdk

names=($(cat sids.txt2))

/projects/evcon\@colostate.edu/gatk-4.2.0.0/gatk --java-options "-Xmx4g" HaplotypeCaller \
--tmp-dir tmp \
-R /projects/evcon\@colostate.edu/ref/Canis_familiaris.CanFam3.1.dna.toplevel.fa \
-O ${names[${SLURM_ARRAY_TASK_ID}]}.vcf \
-I ${names[${SLURM_ARRAY_TASK_ID}]}.bqsr.bam 
