#! /bin/bash
#SBATCH -c 4
#SBATCH --partition=shas
#SBATCH --qos=normal
#SBATCH -t 24:00:00
#SBATCH -N 1
#SBATCH --mail-type=END
#SBATCH --mail-user=evan.conaway@gmail.com
#SBATCH --array=0-9
#SBATCH --mem=20000
#SBATCH --mail-type=BEGIN
ml jdk

names=($(cat sids.txt))

mixcr analyze shotgun -f -t 4 \
--library imgt \
--species dog \
--starting-material dna \
../trimed_reads/${names[${SLURM_ARRAY_TASK_ID}]}_1_val_1.fq.gz \
../trimed_reads/${names[${SLURM_ARRAY_TASK_ID}]}_2_val_2.fq.gz \
${names[${SLURM_ARRAY_TASK_ID}]}
