#!/bin/bash
#SBATCH --partition=shas
#SBATCH --qos normal 
#SBATCH -t 7:00:00
#SBATCH -N 1
#SBATCH --mail-type=END
#SBATCH --mail-user=evan.conaway@gmail.com 
#SBATCH --mem=60000


PATH=/projects/evcon\@colostate.edu/jre1.8.0_161/bin/:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/bin:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/bowtie:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/bowtie2:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/bwa:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/blat:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/star/source/:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/liftover:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/seqtk:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/sratoolkit/bin:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/velvet/:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/fatotwobit/:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/lzop/src/:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/coreutils/src/:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/pigz/:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/samtools/:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/bbmap/:$PATH
PATH=/projects/evcon\@colostate.edu/fusioncatcher/tools/picard/:$PATH
fusioncatcher-build \
-g 'canis_familiaris' \
-o fc_cf.2019,11,04 \
-w 'uswest.ensembl.org'



