#! /bin/bash
#SBATCH --partition=smem
#SBATCH --qos=normal
#SBATCH -t 3-00:00:00
#SBATCH -N 1
#SBATCH --mail-type=END
#SBATCH --mail-type=BEGIN
#SBATCH --mail-user=evan.conaway@gmail.com
#SBATCH --mem=40000

ml jdk
/projects/evcon\@colostate.edu/gatk-4.2.0.0/gatk --java-options "-Xmx4g" HaplotypeCaller \
--tmp-dir tmp \
-R /projects/evcon\@colostate.edu/ref/Canis_familiaris.CanFam3.1.dna.toplevel.fa \
-O CIC94767.g.vcf.gz \
-ERC GVCF \
-I CIC94767.bqsr.bam
