#! /bin/bash
#SBATCH --partition=shas
#SBATCH --qos=normal 
#SBATCH -t 6:00:00
#SBATCH -N 1
#SBATCH --mail-type=END
#SBATCH --mail-user=evan.conaway@gmail.com
#SBATCH --mem=60000
#SBATCH -c 8
ml perl
export PERL_LOCAL=/projects/$USER/perl_local
eval $(perl -I$PERL_LOCAL/lib/perl5 -Mlocal::lib=$PERL_LOCAL)
PATH=$PATH:/projects/evcon\@colostate.edu/STAR-2.5.3a/bin/Linux_x86_64/
/projects/evcon\@colostate.edu/RSEM-1.3.1/rsem-calculate-expression \
--paired-end --star-gzipped-read-file --star --p 8 \
../PTL3_BOX_1_val_1.fq.gz ../PTL3_BOX_2_val_2.fq.gz \
/projects/evcon\@colostate.edu/RSEM-1.3.1/ref/dog PTL3_BOX
