#! /bin/bash
#SBATCH --partition=shas
#SBATCH --qos normal 
#SBATCH -t 10:00:00
#SBATCH -N 1
#SBATCH --mem=60000 
#SBATCH --mail-type=END
#SBATCH --mail-user=evan.conaway@gmail.com
module load gcc/6.1.0
module load perl/5.24.0
export PERL_LOCAL=/projects/$USER/perl_local
eval $(perl -I$PERL_LOCAL/lib/perl5 -Mlocal::lib=$PERL_LOCAL)
perl -Mforks -e 'use threads'
export PATH=/projects/evcon\@colostate.edu/STAR-2.6.1c/bin/Linux_x86_64/:$PATH
export PATH=/projects/evcon\@colostate.edu/hmmer-3.1b2-linux-intel-x86_64/binaries/:$PATH
export PATH=/projects/evcon\@colostate.edu/ncbi-blast-2.7.1+/bin/:$PATH
export PATH=/projects/evcon\@colostate.edu/STAR-Fusion-v1.5.0/:$PATH
module load jdk/1.8.0
STAR-Fusion \
--genome_lib_dir /projects/evcon\@colostate.edu/ref/ctat_genome_lib_build_dir/ \
--examine_coding_effect \
--FusionInspector validate \
--FusionInspector inspect \
--left_fq ATE_M1_1_val_1.fq.gz \
--right_fq ATE_M1_1_val_1.fq.gz \
--output_dir ATE_M1
