#!/bin/bash
#SBATCH --partition=shas
#SBATCH --qos normal 
#SBATCH -t 10:00:00
#SBATCH -N 1
#SBATCH --mail-type=END
#SBATCH --mail-user=evan.conaway@gmail.com 
#SBATCH --mem=60000
#SBATCH -c 10 
tophat2 \
--fusion-search \
-p 10 \
-r 150 \
-o aml_thf \
-G /projects/evcon@colostate.edu/ref/Canis_familiaris.CanFam3.1.97.gff3 \
/projects/evcon\@colostate.edu/ref/canfam3 \
AMLAH723_1_val_1.fq.gz AMLAH723_2_val_2.fq.gz 

